definitions:
  domain.CardData:
    properties:
      cvv:
        type: string
      expiry_date:
        type: string
      holder:
        type: string
      number:
        type: string
    type: object
  domain.CredentialData:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  domain.Credentials:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  domain.FileData:
    properties:
      extension:
        type: string
      name:
        type: string
    required:
    - extension
    - name
    type: object
  domain.TextData:
    properties:
      content:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/data/card/{label}:
    get:
      consumes:
      - application/json
      description: Получает данные кредитной карты пользователя по метке
      parameters:
      - description: Bearer токен
        in: header
        name: Authorization
        required: true
        type: string
      - description: Метка для идентификации данных
        in: path
        name: label
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CardData'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить данные кредитной карты
      tags:
      - data
    post:
      consumes:
      - application/json
      description: Сохраняет данные кредитной карты пользователя
      parameters:
      - description: Bearer токен
        in: header
        name: Authorization
        required: true
        type: string
      - description: Метка для идентификации данных
        in: path
        name: label
        required: true
        type: string
      - description: Данные кредитной карты
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/domain.CardData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Сохранить данные кредитной карты
      tags:
      - data
  /api/data/credential/{label}:
    get:
      consumes:
      - application/json
      description: Получает пару логин/пароль пользователя по метке
      parameters:
      - description: Bearer токен
        in: header
        name: Authorization
        required: true
        type: string
      - description: Метка для идентификации данных
        in: path
        name: label
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CredentialData'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить учетные данные
      tags:
      - data
    post:
      consumes:
      - application/json
      description: Сохраняет пару логин/пароль пользователя
      parameters:
      - description: Bearer токен
        in: header
        name: Authorization
        required: true
        type: string
      - description: Метка для идентификации данных
        in: path
        name: label
        required: true
        type: string
      - description: Учетные данные
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/domain.CredentialData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Сохранить учетные данные
      tags:
      - data
  /api/data/text/{label}:
    get:
      consumes:
      - application/json
      description: Получает произвольный текст пользователя по метке
      parameters:
      - description: Bearer токен
        in: header
        name: Authorization
        required: true
        type: string
      - description: Метка для идентификации данных
        in: path
        name: label
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.TextData'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить текстовые данные
      tags:
      - data
    post:
      consumes:
      - application/json
      description: Сохраняет произвольный текст пользователя
      parameters:
      - description: Bearer токен
        in: header
        name: Authorization
        required: true
        type: string
      - description: Метка для идентификации данных
        in: path
        name: label
        required: true
        type: string
      - description: Текстовые данные
        in: body
        name: text
        required: true
        schema:
          $ref: '#/definitions/domain.TextData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Сохранить текстовые данные
      tags:
      - data
  /api/files/download:
    get:
      consumes:
      - application/json
      description: Генерирует ссылку для скачивания файла с сервера
      parameters:
      - description: Bearer токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      - description: Метка файла
        in: query
        name: label
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Успешная генерация ссылки, возвращает URL для скачивания файла
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка в формате запроса
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Пользователь не авторизован
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Файл не найден
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Скачивание файла
      tags:
      - files
  /api/files/upload:
    post:
      consumes:
      - application/json
      description: Генерирует ссылку для загрузки файла на сервер
      parameters:
      - description: Bearer токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      - description: Информация о загружаемом файле
        in: body
        name: fileData
        required: true
        schema:
          $ref: '#/definitions/domain.FileData'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная генерация ссылки, возвращает URL для загрузки файла
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка в формате запроса
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Пользователь не авторизован
          schema:
            additionalProperties:
              type: string
            type: object
        "413":
          description: Превышен максимальный размер файла
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Загрузка файла
      tags:
      - files
  /api/user/login:
    post:
      consumes:
      - application/json
      description: Авторизует пользователя в системе и возвращает токен авторизации
      parameters:
      - description: Учетные данные пользователя
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/domain.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная авторизация, возвращает статус и токен в заголовке
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка в формате запроса
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Неверный логин или пароль
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Авторизация пользователя
      tags:
      - auth
  /api/user/register:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя в системе и возвращает токен авторизации
      parameters:
      - description: Учетные данные пользователя
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/domain.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная регистрация, возвращает статус и токен в заголовке
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка в формате запроса
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Пользователь с таким логином уже существует
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Регистрация нового пользователя
      tags:
      - auth
swagger: "2.0"
