name: Build Client

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build client for all platforms
        run: make build-client-all

      - name: Archive builds
        run: |
          mkdir -p artifacts
          cp build/gophkeeper-client-windows-amd64.exe artifacts/
          cp build/gophkeeper-client-linux-amd64 artifacts/
          cp build/gophkeeper-client-darwin-amd64 artifacts/
          cp build/gophkeeper-client-darwin-arm64 artifacts/
          tar -czvf artifacts/gophkeeper-client-builds.tar.gz -C artifacts .

      - name: Upload builds
        uses: actions/upload-artifact@v3
        with:
          name: gophkeeper-client-builds
          path: artifacts/gophkeeper-client-builds.tar.gz
